# Generated by Django 5.2.12 on 2026-03-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('total_units', models.IntegerField(default=0)),
                ('handover_date', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('exterior_video_url', models.URLField(blank=True)),
                ('interior_video_url', models.URLField(blank=True)),
                ('story_video_url', models.URLField(blank=True)),
                ('highlight_video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Standard Payment Plan', max_length=200)),
                ('installment_number', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('due_when', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_type', models.CharField(choices=[('airport', 'Airport'), ('mall', 'Mall'), ('hospital', 'Hospital'), ('beach', 'Beach'), ('school', 'School'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='other', max_length=20)),
                ('distance_km', models.FloatField(default=0)),
                ('travel_time_minutes', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.CharField(max_length=50)),
                ('floor_plan_image_url', models.URLField(blank=True)),
                ('units_on_floor', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('recreation', 'Recreation'), ('kids', 'Kids'), ('wellness', 'Wellness'), ('social', 'Social'), ('retail', 'Retail'), ('other', 'Other')], default='other', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('lobby', 'Lobby'), ('gym', 'Gym'), ('pool', 'Pool'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('other', 'Other')], default='other', max_length=20)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('studio', 'Studio'), ('1br', '1 Bedroom'), ('2br', '2 Bedrooms'), ('3br', '3 Bedrooms'), ('penthouse', 'Penthouse'), ('villa', 'Villa'), ('mansion', 'Mansion'), ('retail', 'Retail')], max_length=20)),
                ('total_units_available', models.IntegerField(default=0)),
                ('area_sqft_min', models.FloatField(default=0)),
                ('area_sqft_max', models.FloatField(default=0)),
                ('starting_price_aed', models.FloatField(default=0)),
                ('floor_plan_image_url', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('area_sqft', models.FloatField(default=0)),
                ('area_sqm', models.FloatField(default=0)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projects.unittype')),
            ],
        ),
    ]
