# Generated by Django 5.2.12 on 2026-03-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brochure_url',
            field=models.URLField(blank=True),
        ),
    ]
