# Generated by Django 5.2.12 on 2026-03-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_brochure_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='UAE', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='AED', max_length=10),
        ),
    ]
